version: '3.8'
services:
  api-prod:
    build: .
    ports:
      - 5000:5000
    environment:
      - PORT=5000
      - MONGO_USER=root
      - MONGO_PASSWORD=rootpw
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpw
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
