version: '3.8'
services:
  api-prod:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis        

  nginx:
    restart: always    
    image: nginx:1.25-alpine
    container_name: nginx-prod
    ports:
      - 80:80
    volumes:
      - ./nginx/default-prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-prod    

volumes:
  mongo-db:
